logging:
  level:
    root: debug
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://35.194.109.236:3306/score?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultQueries=true
    username: root
    password: fuck1234
  redis:
    database: 0
    host: localhost
    port: 6379
mybatis:
  type-aliases-package: com.dragon.scoreapi.model
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
server:
  port: 8000
  servlet:
    context-path: /app

file:
  path: /home/data