logging:
  level:
    root: debug
spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://35.194.109.236:3306/score?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultQueries=true
    username: root
    password: fuck1234
server:
  port: 8100